### ISSUE TITLE
Modern Browser

### ISSUE THREAD

**Issue by yamsergey** [BerryFarm/berrymuch#27]
Blackberry browser is really good, but quite outdated now. 

I wonder if we can build a special version of chromium (BLINK and V8) for BB10 specifically or for Android runtime.

**Comment by vaskas** [comment]
Have you tried Fennec 68.2 by XcrazyS? https://forums.crackberry.com/blackberry-10-os-f269/adapted-android-applications-tips-tricks-1173929/index6.html#post13458529

It's bloody amazing. See the whole thread too.

**Comment by yamsergey** [comment]
I will check. But I was mostly thinking about the library which I can add to an app.

**Comment by vaskas** [comment]
https://github.com/jonathan-reisdorf/bb10-minimalistic-browser (BEOL) but it hasn't been updated in a while but seems like what you are looking for.

For an end user app the best one is https://kiwibrowser.com/. However in my experience Fennec is much faster and more stable.

**Comment by vaskas** [comment]
Seems like Intel abandoned the Crosswalk project so BEOL isn't likely to be updated (https://forums.crackberry.com/blackberry-10-apps-f274/prototype-alternate-bb10-optimized-browser-1142073/index13.html). Also looks like Chromium 73 is the last pre-4.4 compatible build (https://android-apk.org/org.chromium.chrome/)

I am personally more excited about Fennec because it made it from a slow buggy behemoth at v57.04 into a non-working v58 and back into a stable and fast v68.2.

**Comment by yamsergey** [comment]
Ok, I see, not a lot we can achieve right now. I'm planning to move this discussion into wiky, any objections?

**Comment by vaskas** [comment]
Good idea :+1:
