### ISSUE TITLE
berrymuch git repo too big: let's split it ?

### ISSUE THREAD

**Issue by berryamin** [BerryFarm/berrymuch#30]
Hi Audacious hackers !

  when working on berrymuch via an online server, I find it very big and am looking for some options .. du -skh gives nearly 1Go.

   I think probably much comes from the former bootstrap/ subpart .. IMHO, we should move bootstrap/ to a dedicated git module. Preserving ports/ and ports-wip/, which contain only real programs, not tools to compile them.

   This would allow to distinguish two classes of users as well:
- simple users of the binaries
- more advanced users who want to compile on the target

I'm more of the second part, due to some good reasons:
- gcc slow on target
- many files below /accounts/1000/shared/documents/ slows down bb10 very much
- we have an almost perfect DockerImage to deploy buildhost on a fast, online hardware

What do you think about this ?

**Comment by vaskas** [comment]
There are 2 problems:

1. A full git checkout is near 1Gb:

What takes up most of the disk space is gcc, as you know it's fully checked into this repo because we wanted not to rely on foundry27 which requires a separate login and may be closed to public one day. A good approach would be to move gcc out into another (say `BerryFarm/gcc`) repo, then change `build.sh` so that it downloads from there.

2. The berrymuch binary release ships developer tools as well as end user progs meaning the distro is quite fat on the device.

I don't know whether it actually slows the phone down. I think what would ultimately solve this is a packaging system and a small install script. The install script will create the directories and a profile symlink and bring in the package manager. Then the users can use the manager to install whatever programs they desire including gcc and its siblings.

**Comment by berryamin** [comment]
Hi !
 I've played a little bit with this happy gist from k1000 (many thanks to him);
https://gist.github.com/k1000/1151135
Pruned ports/gcc using a single line command !
Resulting repository:

<pre>
pokchoy@kimchi:~/berrymuch$ du -skh
220M
</pre>

I vote "yes" for gcc pruning / move to a dedicated repo !

**Comment by vaskas** [comment]
I agree @berryamin - would you be okay to do this? Let's host the gcc under BerryFarm also

**Comment by berryamin** [comment]
Ok done :)
Please check out 
https://github.com/BerryFarm/gcc

**Comment by vaskas** [comment]
We still need gcc in ports! But referencing the codebase from https://github.com/BerryFarm/gcc. I suggest you make a tarball release in https://github.com/BerryFarm/gcc and create a quick port in berrymuch which would download and compile it exactly the way it did but from the new source

**Comment by berryamin** [comment]
Done
